.dvParseAtom <- function(xml){
    xmllist <- xmlToList(xml)
    xmlout <- list( bibliographicCitation = xmllist$bibliographicCitation,
                    generator = xmllist$generator,
                    id = xmllist$id)
    xmlout$objectId <- strsplit(xmlout$id,'study/')[[1]][2]
    xmlout$xml <- xml
    class(xmlout) <- 'dvStudyAtom'
    return(xmlout)
}

print.dvStudyAtom <- function(x){
    cat('Citation:',x$bibliographicCitation,'\n')
    cat('ObjectId:',x$objectId,'\n')
    cat('Study URI:',x$id,'\n')
    cat('Generated by:',x$generator['uri'],x$generator['version'],'\n')
    invisible(x)
}
